# Generated by Django 5.2.1 on 2025-06-03 01:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25),
        ),
    ]
